[general]
import=["./.alacritty.base.toml"]

[font]
size = 8.5

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
## for Linux
#decorations = "None"
## for i3wm
decorations = "full"
dynamic_padding = true
opacity = 0.9
startup_mode = "Windowed"
