[general]
import=["./.alacritty.base.toml"]

[font]
size = 14.6

[font.normal]
style = "Regular"

[font.bold]
family = "Monaco"
style = "Bold"

[font.italic]
family = "Monaco"
style = "Italic"

#[terminal.shell]
#args = "tmux attach || tmux new -s default"
#program = "/usr/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0

[window.position]
x = 100
y = 1600
